/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Michal
 */
public class formOneQuotation extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(formOneQuotation.class.getName());
    int QuotationID = 0;

    // Init
    DefaultTableModel model;
    formManageQuotations previousForm = null;

    public formOneQuotation() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        // Fetches Table model and makes table non-editable
        model = (DefaultTableModel) jTable_QuotationDetails.getModel();
        jTable_QuotationDetails.setDefaultEditor(Object.class, null);

        // Sets up the table header to be a bit larger
        JTableHeader header = jTable_QuotationDetails.getTableHeader();
        header.setFont(new Font("Dialog", Font.PLAIN, 14));

        // Makes some of the input fields uneditable
        JTextField[] fields = {txtQuotationID, txtCustomer, txtEmployee, txtDateCreated, txtTotal};
        Utility.setEditable(fields, false);

        // Adjusting the header widths
        jTable_QuotationDetails = Utility.setColumnWidths(jTable_QuotationDetails, new int[]{300, 100, 60, 90, 90});
    }

    public void loadQuotation() {

        String query = "SELECT CONCAT(tblCustomer.forename,' ',tblCustomer.surname) AS customerFullName,"
                + " CONCAT(tblEmployee.forename,' ',tblEmployee.surname) AS employeeFullName, date_created"
                + " FROM tblQuotation"
                + " INNER JOIN tblCustomer ON tblQuotation.customer_id=tblCustomer.customer_id"
                + " INNER JOIN tblEmployee ON tblQuotation.employee_id=tblEmployee.employee_id"
                + " WHERE quotation_id = ?";

        try (Connection conn = sqlManager.openConnection()) {
            // Query Setup & Execution
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, QuotationID);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Loads all the data from the DB into the JTextFields
                txtQuotationID.setText(String.valueOf(QuotationID));
                txtCustomer.setText(rs.getString(1));
                txtEmployee.setText(rs.getString(2));
                txtDateCreated.setText(String.valueOf(rs.getDate(3)));

                double Total = loadQuotationDetails(QuotationID);
                txtTotal.setText(Utility.formatCurrency(Total));

            } else {
                logger.log(Level.WARNING, "No quotation with this quotation_id was found");
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "SQLException");
        }

    }

    private double loadQuotationDetails(int quotationID) {
        // Init
        double QuotationTotal = 0;
        String query = "SELECT description, category_id, quantity, unit_price "
                + "FROM tblQuotationDetail "
                + "WHERE quotation_id = ?";

        try (Connection conn = sqlManager.openConnection()) {
            // Query Setup & Execution
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, quotationID);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                // Pre-processing
                double itemTotal = rs.getInt(3) * rs.getDouble(4);
                QuotationTotal += itemTotal;
                String itemCategory = sqlManager.getCategory("tblItemCategory", "category_id", rs.getInt(2));
                String sItemTotal = Utility.formatCurrency(itemTotal);
                String sUnitPrice = Utility.formatCurrency(rs.getDouble(4));

                // Adds the quotation item to the table
                model.addRow(new Object[]{rs.getString(1), itemCategory, rs.getInt(3), sUnitPrice, sItemTotal});
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "SQLException");
        }

        return QuotationTotal;
    }

    // Used when the form is opened from within another form
    public formOneQuotation getFrame() {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuotationID = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblDateCreated = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtQuotationID = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtEmployee = new javax.swing.JTextField();
        txtDateCreated = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_QuotationDetails = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        btnFormat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Quotation");

        lblQuotationID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblQuotationID.setText("Quotation ID:");

        lblCustomer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCustomer.setText("Customer:");

        lblEmployee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEmployee.setText("Employee:");

        lblDateCreated.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDateCreated.setText("Date created:");

        lblTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTotal.setText("Total:");

        txtQuotationID.setEditable(false);

        jTable_QuotationDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Category", "Quantity", "Unit Price", "Item Total"
            }
        ));
        jScrollPane1.setViewportView(jTable_QuotationDetails);

        btnFormat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFormat.setText("Format into Word Document");
        btnFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuotationID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuotationID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDateCreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(lblEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuotationID)
                    .addComponent(txtQuotationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployee)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateCreated)
                    .addComponent(txtDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // NEA OBJECTIVE 7.1: Allow user to specify which receipt should be turned into a Microsoft-Word Document.
    // This button is for converting the quotation into a Word document
    private void btnFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatActionPerformed
        formFormatIntoWord form = new formFormatIntoWord().getFrame();
        form.receiptID = QuotationID;
        form.RECEIPT_TYPE = formFormatIntoWord.QUOTATION;
        form.setDocument();
        form.setVisible(true);
    }//GEN-LAST:event_btnFormatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formOneQuotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formOneQuotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formOneQuotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formOneQuotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formOneQuotation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_QuotationDetails;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDateCreated;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblQuotationID;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtDateCreated;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtQuotationID;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
